---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rollout-active
spec:
  selector:
    app: nginx-rollout
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rollout-preview
spec:
  selector:
    app: nginx-rollout
  ports:
    - port: 80
      targetPort: 80
