apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Olga-Galsan/US-Mobile-project
    targetRevision: main
    path: gitops-repo/nginx-rollout
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
